CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(255) NOT NULL,
  `passwordHash` CHAR(40) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `userName` (`userName`)
) ENGINE = InnoDB  DEFAULT CHARSET = latin1 AUTO_INCREMENT = 100 ;

CREATE TABLE IF NOT EXISTS `products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `productName` VARCHAR(255) NOT NULL,
  `vendor` VARCHAR(255) NOT NULL,
  `imagePath` VARCHAR(255) NOT NULL,
  `userId` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`userId`) REFERENCES `users`(`id`)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 AUTO_INCREMENT = 100;

CREATE TABLE IF NOT EXISTS `ratings` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `comment` TEXT(3000),
  `rank` TINYINT UNSIGNED NOT NULL,
  `createDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `productId` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`productId`) REFERENCES `products`(`id`) ON UPDATE CASCADE ON DELETE CASCADE,
  CHECK (`rank` < 6)
) ENGINE = InnoDB DEFAULT CHARSET = latin1 AUTO_INCREMENT = 100;